extends: default
ignore: |
  .venv/
  node_modules/
  .git/
  __pycache__/
  *.egg-info/
rules:
  document-start: disable
  line-length:
    max: 160
    level: warning
  truthy: disable
  comments:
    min-spaces-from-content: 1
    require-starting-space: false
  comments-indentation: disable
