[changelog]
# Required for remote links in the changelog
owner = "smorin"
repository = "py-launch-blueprint"

[commit_types]
feat = { changelog_title = "Features", semver = "minor" }
fix = { changelog_title = "Bug Fixes", semver = "patch" }
docs = { changelog_title = "Documentation", semver = "none" }
style = { changelog_title = "Styling", semver = "none" }
refactor = { changelog_title = "Refactors", semver = "none" }
perf = { changelog_title = "Performance", semver = "patch" }
test = { changelog_title = "Tests", semver = "none" }
chore = { changelog_title = "Miscellaneous Tasks", semver = "none" }
