name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Install UV
      uses: astral-sh/setup-uv@v5

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # Install the required dependencies (pytest, pytest-cov, requests, click)
    - name: Install dependencies
      run: |
        pip install pytest pytest-cov requests click

    # Install the package itself
    - name: Install the package
      run: |
        pip install .

    # Optionally, install other project dependencies
    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run tests with coverage
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v4

    - name: Run type checker
      run: uvx mypy py_launch_blueprint/

    - name: Check linters
      run: uvx ruff check py_launch_blueprint/

  security:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Safety CLI to check for vulnerabilities
      uses: pyupio/safety-action@v1
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}
        args: --detailed-output
