name: Manual PR Security Review

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: string
      reviewer:
        description: 'Security Reviewer Name'
        required: true
        type: string

jobs:
  security-review:
    runs-on: ubuntu-latest
    environment: security-review
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.inputs.pr_number }}/head

      - name: Run Safety CLI to check for vulnerabilities
        uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
          args: --detailed-output

      - name: Update PR Comment with Security Scan Results
        uses: actions/github-script@v7
        with:
          script: |
            const safetyOutput = `${{ steps.safety.outputs.cli-output }}`;
            const safetyExitCode = '${{ steps.safety.outputs.exit-code }}';
            const safetyStatus = safetyExitCode === '0' ? '✅ PASSED' : '❌ FAILED';

            const checklist = `
            ## Security Review Results

            Reviewer: @${{ github.event.inputs.reviewer }}

            ### Safety CLI Scan Status: ${safetyStatus}

            \`\`\`
            ${safetyOutput}
            \`\`\`

            `;

            await github.rest.issues.createComment({
              issue_number: context.payload.inputs.pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: checklist
            });
