##
## Copyright (c) 2025, Steve Morin
##
## Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##
name: Manual PR Security Review

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: string
      reviewer:
        description: 'Security Reviewer Name'
        required: true
        type: string

jobs:
  security-review:
    runs-on: ubuntu-latest
    environment: security-review
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.inputs.pr_number }}/head

      - name: Run Safety CLI to check for vulnerabilities
        uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
          args: --detailed-output

      - name: Update PR Comment with Security Scan Results
        uses: actions/github-script@v7
        with:
          script: |
            const safetyOutput = `${{ steps.safety.outputs.cli-output }}`;
            const safetyExitCode = '${{ steps.safety.outputs.exit-code }}';
            const safetyStatus = safetyExitCode === '0' ? '✅ PASSED' : '❌ FAILED';

            const checklist = `
            ## Security Review Results

            Reviewer: @${{ github.event.inputs.reviewer }}

            ### Safety CLI Scan Status: ${safetyStatus}

            \`\`\`
            ${safetyOutput}
            \`\`\`

            `;

            await github.rest.issues.createComment({
              issue_number: context.payload.inputs.pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: checklist
            });
